config/routes.rb
Rails.application.routes.draw do
  root to:'homes#top'
  get 'books' => 'books#index'
 resources :booker

   get 'books/:id' => 'books#show', as: 'book'
     get 'books/:id/edit' => 'books#edit', as: 'edit_book'
       patch 'book/:id' => 'books#update', as: 'update_book'
         delete 'books/:id' => 'books#destroy', as: 'destroy_list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    #Viewに渡すインスタンス変数に空のmodelオブジェクトを生成する。
    @list = List.new
  end

  def create
    @book = Book.new(books_params)
    if @book.save
      flash[:notice] = "successfully"
      render :edit
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @error_message = [:alert]
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    @book.update(books_params)
    if @book.save
      flash[:notice] = "successfully"
    redirect_to @book
    else
    @books = Book.all
    flash.now[:alert] ="更新に失敗しました。"
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

 private
  # ストロングパラメータ
  def books_params
   params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

  <%= link_to 'show', book_path(@book) %>
|
<a class="back" href="/books">Back</a>

<% end %>

app/views/books/index.html.erb
<!DOCTYPE html>
  <%= stylesheet_link_tag 'books' %>
<html>

<head>
</head>

<h1>Books</h1>

<tr>
  <th>Title</th>
  <th>Body</th><br>
  <th colspan="3"></th>

</tr>

<% @books.each do |book| %>
<table class="table">
  <tr class="tr">
    <td><%= book.title %></td>
      <td><span class="book-body"><%= book.body %></span></td>
      <td>
      <td><span><%= link_to "show", "/books/#{book.id}" %></span></td>
      <td><span><%= link_to "edit", "/books/#{book.id}/edit" %></span></td>
      <td><span><%= link_to "destroy", "books/#{book.id}", method: :delete, "data-confirm" => "Are you sure？" %></span></td>
      </td>
  </tr>

</table>
<% end %>

<h2>New book</h2>

 <% if @book.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved:</h2>
       <ul>
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
   <% end %>


<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h2>Title</h2>
<p><%= @book.title %></p>

<h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id)  %>
|
<a class="back" href="/books">Back</a>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<%= link_to "start", "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <main>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>    <%= yield %>
   </main>
  </body>
</html>